#!/bin/bash
docker build -t gravity2017/mmp:ravi03 .
docker run -itd --name=sample03 gravity2017/mmp:ravi03
docker logs sample03
docker cp sample03:/data/coverage.xml .
docker cp sample03:/data/test_report.xml .
docker cp sample03:/data/pep8.out .
cat ~/my_password.txt | docker login -u gravity2017 --password-stdin
x=$(cat test_report.xml | sed -e 's/.*failures=\"//;s/\" name.*//')
if [ $x -eq 0 ]; then docker push gravity2017/mmp:ravi03 ; fi
sleep 5m
